/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : eeprom_info.inc
* Description : including adce module all header files
* Author: qq
* Date: 2018-05-29
******************************************************************************/

/* check of multiple include */
#ifndef _DEPM_INFO_INC_
#define _DEPM_INFO_INC_


/* Files for including */
#include <hidef.h>
#include "derivative.h"
#include "yd_typedefs.h"
#include "mc9s12g128.h"
#include "depm_public.h"
#include "depm_private.h"
#include "depm_cfg.h"
#include "wdt_public.h"

#endif /*_DEPM_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0             qq           2018-05-29             Initial
*
*===========================================================================*/
