/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : mcom_info.inc
* Description : including the MCOM module all header files
* Author: lzx
* Date: 2018-06-05
******************************************************************************/

/* check of multiple include */
#ifndef _MCOM_INFO_INC_

#define _MCOM_INFO_INC_


/* Files for including */
#include <cdef21489.h>
#include <def21489.h>
#include <sru.h>
#include <signal.h>
#include <sysreg.h>
#include <services\int\adi_int.h>


#include "mcom_public.h"
#include "mcom_private.h"
#include "mcom_cfg.h"
#include "../../yd_typedefs.h"
#include "math.h"
#include "../../driver/SPIB/spib_public.h"
#include<string.h>

#endif /*_MCOM_INFO_INC_*/


/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       lzx      2018-06-05      Initial
*
*===========================================================================*/
