/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : dspi_info.inc
* Description : including DSPI driver header files.
* Author: Jason.Sun
* Date: 2018-05-24
******************************************************************************/

/* check of multiple include */
#ifndef _DSPI_INFO_INC_

#define _DSPI_INFO_INC_

/* Files for including */
#include <hidef.h>
#include "derivative.h"
#include "yd_typedefs.h"
#include "dspi_cfg.h"
#include "dspi_private.h"
#include "dspi_public.h"
#include "bat_public.h"
#endif /* _DSPI_INFO_INC_ */


/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Jason.Sun      2018-05-24      Initial
*
*===========================================================================*/

