/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : dgpio_cfg.h
* Description : config infomation of DGPIO driver.
* Author: Jason.Sun
* Date: 2018-05-18
******************************************************************************/

/* check of multiple include */
#ifndef _DGPIO_INFO_INC_

#define _DGPIO_INFO_INC_

/* Files for including */
#include <hidef.h>
#include "derivative.h"
#include "dgpio_cfg.h"
#include "dgpio_private.h"
#include "dgpio_public.h"

#endif /* _DGPIO_INFO_INC_ */

/*----------------- End of file -----------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Jason.Sun      2018-05-18      Initial
*
*===========================================================================*/


