/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : sys_info.inc
* Description :including sys module all header files.
* Author:Liuyingying
* Date: 2017-6-30
******************************************************************************/

/* check of multiple include */
#ifndef _SYS_INFO_INC_

#define _SYS_INFO_INC_


/*---------------driver-------------*/
//#include "../../driver/IIS/iis_public.h"
//#include "../../driver/SPI/spi_public.h"
//#include "../../driver/SPIB/spib_public.h"
/*---------------app-------------*/

/*-------------app--------------*/
#include "../FIFO/fifo_public.h"
#include "../LEVEL/level_public.h"
#include "../MDATA/mdata_public.h"
#include "../EVT/evt_public.h"
#include "../../yd_typedefs.h"

#include "sys_cfg.h"
#include "sys_private.h"
#include "sys_public.h"




#endif /*_SYS_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:            Date:             Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       lzx         2018-06-08           Initial
* V2.0       Liuyingying        2017-6-30            modify
*===========================================================================*/
