/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : mdata_info.inc
* Description : including the MDATA module all header files
* Author: lzx
* Date: 2018-06-05
******************************************************************************/

/* check of multiple include */
#ifndef _MDATA_INFO_INC_

#define _MDATA_INFO_INC_


/* Files for including */

#include "../../yd_typedefs.h"
#include "mdata_public.h"
#include "mdata_private.h"
#include "mdata_cfg.h"
#include "../../middleware/MCOM/mcom_public.h"
#include "../LEVEL/level_public.h"
#include "../EVT/evt_public.h"


#endif /*_MDATA_INFO_INC_*/


/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       lzx      2018-06-05      Initial
*
*===========================================================================*/
