#ifndef _TIMER_INFO_INC_
#define _TIMER_INFO_INC_


#include <cdef21479.h>
#include <def21479.h>

#include <sru21479.h>
#include <signal.h>
#include <sysreg.h>
//#include <services\int\adi_int.h>
#include <services\int\adi_int.h>

//#include "../../post_common.h"
#include "../../post_debug.h"


#include "timer_public.h"
#include "timer_private.h"
#include "timer_cfg.h"
#include"../SPIB/spib_info.inc"
//#include "../../app/mdata/mdata_public.h"
#include "../../middleware/MCOM/mcom_public.h"
#endif
