/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : com_info.inc
* Description :including com module all header files.
* Author:Jason.Sun
* Date: 2018-06-05
******************************************************************************/

/* check of multiple include */
#ifndef _COM_INFO_INC_

#define _COM_INFO_INC_
#include <hidef.h>
#include "derivative.h"
#include "yd_typedefs.h"
#include "v_nwm.h"
#include "bat_public.h"
/*#include "ssb_public.h"*/
#include "pwr_public.h"
/*#include "iom_public.h"*/
/*#include "st_public.h"*/
/*#include "stbc_public.h"*/
/*#include "acc_public.h"*/
#include "mute_public.h"
#include "com_cfg.h"
#include "com_private.h"
#include "com_public.h"

#endif /*_COM_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:            Date:             Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Jason.Sun         2018-06-05           Initial
*
*===========================================================================*/






