/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : bat_info.inc
* Description : including bat module all header files
* Author: qq
* Date: 2018-6-6
******************************************************************************/

/* check of multiple include */
#ifndef _BAT_INFO_INC_

#define _BAT_INFO_INC_


/* Files for including */

#include "yd_typedefs.h"
#include "adm_public.h"

#include "bat_public.h"
#include "bat_private.h"
#include "bat_cfg.h"
#endif /*_BAT_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0           qq             2018-06-06             Initial
* *===========================================================================*/