/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : spd_info.inc
* Description : including SPD driver header files.
* Author: qq
* Date: 2018-06-12
******************************************************************************/

/* check of multiple include */
#ifndef _SPD_INFO_INC_
#define _SPD_INFO_INC_

/* Files for including */
#include <hidef.h>
#include "derivative.h"
#include "yd_typedefs.h"
#include "spd_cfg.h"
#include "spd_private.h"
#include "spd_public.h"  
#include "iom_public.h"
#include "spm_public.h"
#include "bat_public.h"
#include "pwr_public.h"

#endif /* _SPD_INFO_INC_ */


/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0             qq         2018-6-12           Initial
*
*===========================================================================*/