/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name :level_info.inc
* Description : includinglevel module all header files
* Author: lzx
* Date: 2018-06-08
******************************************************************************/

/* check of multiple include */
#ifndef _LEVEL_INFO_INC_

#define _LEVEL_INFO_INC_
#include <math.h>

/* Files for including */
#include "../MDATA/mdata_public.h"
#include "level_public.h"
#include "level_private.h"
#include "level_cfg.h"
#include "../../yd_typedefs.h"


#endif /*_LEVEL_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       lzx      2018-06-08      Initial
*
*===========================================================================*/
