/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : mute_info.inc
* Description : including mute module all header files
* Author: qq
* Date: 2018-6-6
******************************************************************************/

/* check of multiple include */
#ifndef _MUTE_INFO_INC_

#define _MUTE_INFO_INC_


/* Files for including */

#include "yd_typedefs.h"
#include "iom_public.h"
#include "spd_public.h"
#include "pwr_public.h"
#include "bat_public.h"
#include "ds_public.h"
#include "com_public.h" 

#include "mute_public.h"
#include "mute_private.h"
#include "mute_cfg.h"
#endif /*_MUTE_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0        qq              2018-06-06             Initial
* *===========================================================================*/