/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : spm_info.inc
* Description : including DIIC driver header files.
* Author: qq
* Date: 2018-06-07
******************************************************************************/

/* check of multiple include */
#ifndef _SPM_INFO_INC_
#define _SPM_INFO_INC_

/* Files for including */
#include <hidef.h>
#include "derivative.h"
#include "yd_typedefs.h"
#include "spm_cfg.h"
#include "spm_private.h"
#include "spm_public.h"  

#include "diic_public.h"
#include "dgpio_public.h"

#endif /* _SPM_INFO_INC_ */


/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0             qq         2018-6-7           Initial
*
*===========================================================================*/