#ifndef _UART_INFO_INC_
#define _UART_INFO_INC_

#define __ADSP21489__

#include <cdef21489.h>
#include <def21489.h>
#include <stdio.h>
#include <sru.h>
#include <signal.h>
#include <sysreg.h>
#include <string.h>

#include "../../common/flash.h"
#include "../../post_debug.h"
#include <services\int\adi_int.h>
#include <asm_sprt.h>
#include "uart_public.h"
#include "uart_private.h"
#include "uart_cfg.h"


#endif
