/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : diic_info.inc
* Description : including DIIC driver header files.
* Author: Jason.Sun
* Date: 2018-05-28
******************************************************************************/

/* check of multiple include */
#ifndef _DIIC_INFO_INC_

#define _DIIC_INFO_INC_

/* Files for including */
#include <hidef.h>
#include "derivative.h"
#include "yd_typedefs.h"
#include "diic_cfg.h"
#include "diic_private.h"
#include "diic_public.h"

#endif /* _DIIC_INFO_INC_ */


/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Jason.Sun      2018-05-28      Initial
*
*===========================================================================*/