/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : dcom_info.inc
* Description : including the DCOM module all header files
* Author: lzx
* Date: 2018-06-05
******************************************************************************/

/* check of multiple include */
#ifndef _DCOM_INFO_INC_

#define _DCOM_INFO_INC_


/* Files for including */
#include "dspi_public.h"
#include "dcom_public.h"
#include "dcom_private.h"
#include "dcom_cfg.h"
#include "yd_typedefs.h"
#include "math.h"


#endif /*_DCOM_INFO_INC_*/


/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       lzx      2018-06-05      Initial
*
*===========================================================================*/