/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : ostm_info.inc
* Description : including ostm module all header files
* Author: Jason.Sun
* Date: 2018-05-23
******************************************************************************/

/* check of multiple include */
#ifndef _OSTM_INFO_INC_
#define _OSTM_INFO_INC_


/* Files for including */
#include <hidef.h>
#include "derivative.h"

#include "Yd_typedefs.h"

#include "ostm_public.h"
#include "ostm_private.h"
#include "ostm_cfg.h"
#include "nwd_public.h"
#include "com_public.h"

#endif /*_OSTM_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0      Jason.Sun     2018-05-23      Initial
*
*===========================================================================*/
