/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name :fifo_info.inc
* Description : includingfifo module all header files
* Author: lzx
* Date: 2018-06-08
******************************************************************************/

/* check of multiple include */
#ifndef _FIFO_INFO_INC_

#define _FIFO_INFO_INC_


/* Files for including */
#include "../MDATA/mdata_public.h"
#include "../EVT/evt_public.h"
#include "fifo_public.h"
#include "fifo_private.h"
#include "fifo_cfg.h"
#include "../../yd_typedefs.h"


#endif /*_FIFO_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       lzx      2018-06-08      Initial
*
*===========================================================================*/
