/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : wdt_info.inc
* Description :
* Author: Jason.Sun
* Date: 2018-05-22
******************************************************************************/

/* check of multiple include */
#ifndef _WDT_INFO_INC_

#define _WDT_INFO_INC_

/* Files for including */
#include <hidef.h>
#include "derivative.h"

#include "yd_typedefs.h"
#include "wdt_public.h"
#include "wdt_private.h"

#endif /* _WDT_INFO_INC_ */


/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Jason.Sun      2018-05-22      Initial
*
*===========================================================================*/

