/* (C) Mentor Graphics Corporation */
/* Automatically generated file.   */
/* DO NOT EDIT THIS FILE!          */

#include "volcano6.h"
#include "v_hand.h"
#include "v_msc12s.h"

typedef struct {
	v_uint8 dumy;
} v_fmd_descriptor;
typedef struct {
	v_uint8 dumy;
} v_c_ram ;
typedef struct {
	v_uint8 dumy;
} v_imf_descriptor;
typedef struct {
	v_uint8 dumy;
} v_s_descriptor;

struct v_controller_descriptor V_AROM v_controllers[] = {
{
    (v_fmd_handle)0x000044c8,
    (struct v_c_ram V_RAM * V_RAM_PM)0x00002f00,
    (void V_NVRAM * V_NVRAM_PM)0x000046b0,
    (void V_NVRAM * V_NVRAM_PM)0x00000000,
    v_msc12s_send_frame,
    v_msc12s_send_frames,
    v_msc12s_read_frame,
    v_msc12s_read_frames,
    v_msc12s_tx_pending,
    v_msc12s_set_mode,
    v_msc12s_rx_interrupt_handler,
    v_msc12s_init_controller,
    v_msc12s_connect_controller,
    v_msc12s_disconnect_controller,
    v_msc12s_controller_active,
    v_msc12s_controller_ioctl,
    v_msc12s_tx_interrupt_handler,
    v_msc12s_busoff_interrupt_handler,
    v_msc12s_check_frame,
    (void (*)(v_nwm_recdata*))0,
    (void V_RAM * V_RAM_PM)0x00002f8a,
    (v_uint8)0x01,
    (v_uint8)0x00
},
{	(v_fmd_handle)0,
 	(struct v_c_ram V_RAM * V_RAM_PM)0,
 	(void V_NVRAM * V_NVRAM_PM)0,
 	(void V_NVRAM * V_NVRAM_PM)0,
 	(v_bool (*)(v_c_handle, void V_NVRAM * V_NVRAM_PM))0,
 	(void (*)(v_c_handle, v_frame_map*, v_frame_map*))0,
 	(v_bool (*)(v_c_handle, void V_NVRAM * V_NVRAM_PM))0,
 	(void (*)(v_c_handle))0,
 	(v_bool (*)(v_c_handle))0,
 	(void (*)(v_c_handle, v_fmd_handle))0,
 	(v_imf_handle (*)(v_c_handle))0,
 	(v_uint8 (*)(v_c_handle))0,
 	(void (*)(v_c_handle))0,
 	(void (*)(v_c_handle))0,
 	(v_bool (*)(v_c_handle))0,
 	(v_uint16 (*)(v_c_handle, v_ioctl_op, void *))0,
 	(v_imf_handle (*)(v_c_handle))0,
 	(void (*)(v_c_handle))0,
 	(v_uint8 (*)(v_c_handle, void V_NVRAM * V_NVRAM_PM))0,
 	(void (*)(v_nwm_recdata*))0,
 	(void V_RAM * V_RAM_PM)0,
	0,
	0 }
}; /* end v_controllers[] */

v_uint16 V_AROM v_flag_byte_count = 0x0002;
v_uint8 V_ARAM v_flag_buffer[2];

struct v_fl_descriptor V_AROM v_flags[] = {
{
    (v_s_handle)0x0000428c,
    &v_flag_buffer[0],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    1,
    (v_bool)1,
},
{
    (v_s_handle)0x0000419e,
    &v_flag_buffer[0],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    2,
    (v_bool)1,
},
{
    (v_s_handle)0x000041f3,
    &v_flag_buffer[0],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    4,
    (v_bool)1,
},
{
    (v_s_handle)0x0000406c,
    &v_flag_buffer[0],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    8,
    (v_bool)1,
},
{
    (v_s_handle)0x000040f4,
    &v_flag_buffer[0],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    16,
    (v_bool)1,
},
{
    (v_s_handle)0x00004204,
    &v_flag_buffer[0],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    32,
    (v_bool)1,
},
{
    (v_s_handle)0x0000428c,
    &v_flag_buffer[0],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    64,
    (v_bool)1,
},
{
    (v_s_handle)0x000042f2,
    &v_flag_buffer[0],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    128,
    (v_bool)1,
},
{
    (v_s_handle)0x00004369,
    &v_flag_buffer[1],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    1,
    (v_bool)1,
},
{
    (v_s_handle)0x00004259,
    &v_flag_buffer[1],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    2,
    (v_bool)1,
},
{
    (v_s_handle)0x00004149,
    &v_flag_buffer[1],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    4,
    (v_bool)1,
},
{
    (v_s_handle)0x0000439c,
    &v_flag_buffer[1],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    8,
    (v_bool)1,
},
{
    (v_s_handle)0x000041f3,
    &v_flag_buffer[1],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    16,
    (v_bool)1,
},
{
    (v_s_handle)0x000040f4,
    &v_flag_buffer[1],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    32,
    (v_bool)1,
},
{	(v_s_handle)0,
	(v_uint8 V_ARAM * V_ARAM_PM)0,
	(v_fptr)0,
	(struct v_fl_descriptor V_AROM * V_AROM_PM)0,
	(v_imf_handle)0,
	0,
	0 }
}; /* end v_flags[] */


struct v_fl_descriptor V_AROM v_transmit_flags[] = {
{	(v_s_handle)0,
	(v_uint8 V_ARAM * V_ARAM_PM)0,
	(v_fptr)0,
	(struct v_fl_descriptor V_AROM * V_AROM_PM)0,
	(v_imf_handle)0,
	0,
	0 }
}; /* end v_transmit_flags[] */

v_uint16 V_AROM v_overrun_flag_byte_count = 0x0001;
v_uint8 V_ARAM v_overrun_flag_buffer[1];

struct v_fl_descriptor V_AROM v_overrun_flags[] = {
{	(v_s_handle)0,
	(v_uint8 V_ARAM * V_ARAM_PM)0,
	(v_fptr)0,
	(struct v_fl_descriptor V_AROM* V_AROM_PM)0,
	(v_imf_handle)0,
	0,
	0 }
}; /* end v_overrun_flags[] */


struct v_fl_descriptor V_AROM v_timeout_flags[] = {
{	(v_s_handle)0,
	(v_uint8 V_ARAM * V_ARAM_PM)0,
	(v_fptr)0,
	(struct v_fl_descriptor V_AROM * V_AROM_PM)0,
	(v_imf_handle)0,
	0,
	0 }
}; /* end v_timeout_flags[] */


struct v_t_descriptor V_AROM v_timeouts[] = {
{
    (v_s_handle)0,
    (v_s_handle)0,
    (v_fl_handle)0,
    {
        (v_uint8 V_AROM * V_AROM_PM)0
    },
    0,
    (v_uint16 V_ARAM * V_ARAM_PM)0,
    (v_bool)0 }
}; /* end v_timeouts[] */

v_uint16 V_AROM v_imf_not[] = {0xffff,0xffff,0xffff,0xffff,0xffff};
v_uint8 V_AROM v_imf_inot[] = {0x00,0x00,0x00,0x00,0xff};
v_imf_handle V_AROM v_imf_array = (v_imf_handle)0x000044ac;
v_uint32 V_AROM v_fixed_checksum = 0x5ad69ea9;
v_uint32 V_AROM v_target_checksum = 0xd4764055;
