/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : diag_info.inc
* Description : including the DS module all header files
* Author: lzx
* Date: 2018-06-05
******************************************************************************/

/* check of multiple include */
#ifndef _DS_INFO_INC_
#define _DS_INFO_INC_


/* Files for including */

#include "yd_typedefs.h"
#include "diag_public.h"
#include "diag_private.h"
#include "diag_cfg.h"
//#include "acc_public.h"
//#include "iom_public.h"
//#include "nvm_public.h"
#include "com_public.h"
#include "uart_public.h"
#include "pwr_public.h"
#include "bat_public.h"
#include "ds_public.h"
//#include "test_public.h"

#endif /*_DIAG_INFO_INC_*/


/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       qq      2018-07-18      Initial
*
*===========================================================================*/
