/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name :evt_info.inc
* Description : includingevt module all header files
* Author: lzx
* Date: 2018-06-08
******************************************************************************/

/* check of multiple include */
#ifndef _EVT_INFO_INC_

#define _EVT_INFO_INC_


/* Files for including */
#include "../MDATA/mdata_public.h"
#include "../FIFO/fifo_public.h"
#include "evt_public.h"
#include "evt_private.h"
#include "evt_cfg.h"
#include "../../yd_typedefs.h"

#endif /*_EVT_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       lzx      2018-06-08      Initial
*
*===========================================================================*/
