/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : adce_info.inc
* Description : including adce module all header files
* Author: Jason.Sun
* Date: 2018-05-22
******************************************************************************/

/* check of multiple include */
#ifndef _ADCE_INFO_INC_
#define _ADCE_INFO_INC_


/* Files for including */
#include <hidef.h>
#include "derivative.h"
#include "yd_typedefs.h"
#include "adce_public.h"
#include "adce_private.h"
#include "adce_cfg.h"
#endif /*_ADCE_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0      Jason.Sun     2018-05-22      Initial
*
*===========================================================================*/