/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : iom_info.inc
* Description : including iom module all header files
* Author: qq
* Date: 2018-06-07
******************************************************************************/

/* check of multiple include */
#ifndef _IOM_INFO_INC_

#define _IOM_INFO_INC_


/* Files for including */
#include "yd_typedefs.h"
#include "derivative.h"
#include "dgpio_public.h"
#include "iom_public.h"
#include "iom_private.h"
#include "iom_cfg.h"


#endif /*_IOM_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0             qq          2018-06-07      Initial
*
*===========================================================================*/