/*****************************************************************************
* Copyright (C) 2018 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : adm_info.inc
* Description : including the ADM module all header files
* Author: lzx
* Date: 2018-06-05
******************************************************************************/

/* check of multiple include */
#ifndef _ADM_INFO_INC_

#define _ADM_INFO_INC_


/* Files for including */
#include "adce_public.h"
#include "adm_public.h"
#include "adm_private.h"
#include "adm_cfg.h"
#include "yd_typedefs.h"
#include "math.h"


#endif /*_ADM_INFO_INC_*/


/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       lzx      2018-06-05      Initial
*
*===========================================================================*/